package Analyzer;

/**
 * Classe enum per a codificar tots els possibles tokens.
 */
public enum Type {
    SENCER_CST, CADENA, ID, LOGIC_CST, TIPUS_SIMPLE,

    OP_RELACIONAL,
    SUMA, RESTA, DIV, MUL, DPOINT, OPARENT,
    CPARENT, OCLAU, CCLAU, COMA, SEMICOLON, COLON,

    CONST, PROG, FIPROG, FUNCIO, FUNC, FIFUNC,
    VECTOR, ESCRIURE, LLEGIR, CICLE, FINS, MENTRE,
    FER, FIMENTRE, SI, LLAVORS, SINO, FISI, RETORNAR,
    PERCADA, EN, FIPER, VAR, EOF, TERNARIA, AND, OR, NOT, PERREF, PERVAL, IGUAL, DE
}
