package utils;

/**
 * Classe enum per a codificar els codis d'error.
 */
public enum TypeError {
    WAR_LEX_1, WAR_LEX_2,
	ERR_LEX_1,
	ERR_SIN_1, ERR_SIN_2, ERR_SIN_3, ERR_SIN_4, ERR_SIN_5, ERR_SIN_6, ERR_SIN_7,
    ERR_SIN_8, ERR_SIN_10, ERR_SIN_9,
	ERR_SEM_1, ERR_SEM_2, ERR_SEM_3, ERR_SEM_4, ERR_SEM_5, ERR_SEM_6, ERR_SEM_7, ERR_SEM_8, ERR_SEM_9, ERR_SEM_10,
	ERR_SEM_11, ERR_SEM_12, ERR_SEM_13, ERR_SEM_14, ERR_SEM_15, ERR_SEM_16, ERR_SEM_17, ERR_SEM_18, ERR_SEM_19,
	ERR_SEM_20, ERR_SEM_21, ERR_SEM_22, ERR_SEM_23, ERR_SEM_24,
	WAR_OPC_1, WAR_OPC_2, WAR_OPC_3
}
