/**
 * Created by alexj on 15/2/2017.
 */
public enum Type {
    TOKEN_INT, TOKEN_STRING, TOKEN_ID, TOKEN_LOGIC_CST, TOKEN_LOGIC_OP, TOKEN_INT_TYPE, TOKEN_LOGIC_TYPE,

    TOKEN_EQUALS, TOKEN_SET, TOKEN_GT, TOKEN_GTEQ, TOKEN_LT, TOKEN_LTEQ, TOKEN_DIFF,
    TOKEN_SUM, TOKEN_RES, TOKEN_DIV, TOKEN_MUL, TOKEN_DPOINT, TOKEN_OPARENT,
    TOKEN_CPARENT, TOKEN_OCLAU, TOKEN_CCLAU, TOKEN_COMA, TOKEN_SEMICOLON, TOKEN_COLON,

    TOKEN_DEC_CONST, TOKEN_PROG_INIT, TOKEN_PROG_END, TOKEN_FUNC, TOKEN_FUNC_INIT, TOKEN_FUNC_END,
    TOKEN_PARAM, TOKEN_VECTOR, TOKEN_WRITE, TOKEN_READ, TOKEN_DO_INIT, TOKEN_DO_END, TOKEN_WHILE,
    TOKEN_BUCLE_INIT, TOKEN_WHILE_END, TOKEN_IF, TOKEN_IF_INIT, TOKEN_ELSE, TOKEN_IF_END, TOKEN_RETURN,
    TOKEN_FOR, TOKEN_IN, TOKEN_FOR_END, TOKEN_DEC_VAR, TOKEN_OF, TOKEN_ERR
}
